name: Release Assets

on:
  push:
    tags:
      - "v*"

jobs:
  release_draft:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Draft ${{ github.ref }}
          draft: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  build:
    name: Binary for ${{ matrix.os }}
    needs: release_draft
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            package: lorem-linux-ARCH.tar.gz
          - os: macos-latest
            package: lorem-macos-ARCH.tar.gz
          - os: windows-latest
            package: lorem-windows-ARCH.zip
    steps:
      - uses: actions/checkout@v2

      - name: Use rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Test binary
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install zip
          cd target/release
          zip ../../${{ matrix.package }} lorem.exe

      - name: Package for Linux/UNIX
        if: matrix.os != 'windows-latest'
        run: |
          set -xe
          strip target/release/lorem
          tar -czf ${{ matrix.package }} -C target/release lorem

      - id: asset_name_generator
        name: Set asset name
        shell: bash
        run: |
          echo "::set-output name=name::${{ matrix.package }}" | sed "s/ARCH/$(uname -m)/g"

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.release_draft.outputs.upload_url }}
          asset_path: ${{ matrix.package }}
          asset_name: ${{ steps.asset_name_generator.outputs.name }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
